apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-pipeline
data:
  APP_NAME: "DevOps Pipeline"
  ENVIRONMENT: "production"
  APP_VERSION: "1.0"
  OWNER: "Mounika Vasireddy"